# Generated by Django 5.0.6 on 2024-06-26 18:33

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Dni')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=9, unique=True, verbose_name='Celular')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Femenino')], max_length=9, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='StudyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Centro de estudios')),
            ],
            options={
                'verbose_name': 'Centro de estudios',
                'verbose_name_plural': 'Centros de estudios',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Carrera')),
                ('study_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.studycenter', verbose_name='Centro de estudios')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('internship_start_date', models.DateField(verbose_name='Fecha de inicio de practicas')),
                ('internship_end_date', models.DateField(verbose_name='Fecha final de practicas')),
                ('turn', models.CharField(choices=[('MORNING', 'Mañana'), ('AFTERNOON', 'Tarde')], default=attendance.models.Turn['MORNING'], max_length=9, verbose_name='Turno')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='attendance.student', verbose_name='Datos personales')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attendance.career', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Practicante',
                'verbose_name_plural': 'Practicantes',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='Fecha')),
                ('entry_time', models.TimeField(verbose_name='Hora de entrada')),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.practitioner', verbose_name='Practicante')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
